# syntax=docker/dockerfile:1
ARG WHISPER_MODEL=base
ARG LANG=en
ARG CACHE_HOME=/.cache

FROM ghcr.io/jim60105/whisperx:no_model as cache

# Preload vad model
RUN python3 -c 'from whisperx.vad import load_vad_model; load_vad_model("cpu");'

# Preload fast-whisper
ARG WHISPER_MODEL
RUN python3 -c 'import faster_whisper; model = faster_whisper.WhisperModel("'${WHISPER_MODEL}'")'

FROM ghcr.io/jim60105/whisperx:cache-${WHISPER_MODEL} as load_align

# Preload align models
ARG LANG
COPY load_align_model.py .
RUN for i in ${LANG}; do echo "Aliging lang $i"; python3 load_align_model.py $i; done


FROM ghcr.io/jim60105/whisperx:no_model as final

ARG CACHE_HOME
COPY --link --chown=1001 --from=load_align ${CACHE_HOME} ${CACHE_HOME}

ARG WHISPER_MODEL
ENV WHISPER_MODEL=${WHISPER_MODEL}
ARG LANG
ENV LANG=${LANG}

# Take the first language from LANG env variable
ENTRYPOINT LANG=$(echo ${LANG} | cut -d ' ' -f1); \
    whisperx --model "${WHISPER_MODEL}" --language "${LANG}" "$@" 
