# Check this guide for more information about publishing to ghcr.io with GitHub Actions:
# https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio

# Main workflow trigger that initiates the Docker image build chain
# This workflow has been refactored to trigger a sequence of specialized workflows:
# 1. 01-build-base-images.yml - Builds ubi-no_model and no_model base images
# 2. 02-build-model-cache.yml - Builds model cache images (6 models)
# 3. 03-build-distil-en.yml + 04-build-matrix-images.yml - Parallel builds of final images
name: docker_publish

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
    paths-ignore:
      - "*.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  # Trigger workflow to initiate the build chain
  trigger-build-chain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Workflow chain initialization
        run: |
          echo "=== Docker Build Chain Initiated ==="
          echo "Commit: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Run number: ${{ github.run_number }}"
          echo ""
          echo "This workflow will trigger the following sequence:"
          echo "1. 01-build-base-images.yml - Base images (ubi-no_model, no_model)"
          echo "2. 02-build-model-cache.yml - Model cache images (6 models)"
          echo "3. 03-build-distil-en.yml - Distil English model (parallel)"
          echo "4. 04-build-matrix-images.yml - Full matrix build + tests (parallel)"
          echo ""
          echo "Total expected images: ~175+"
          echo "=== Build Chain Ready ==="
